### ISSUE TITLE
Does not boot from USB after sysupgrade

### ISSUE THREAD

**Issue by func0der** [attila-lendvai/openwrt-auto-extroot#5]
Hey,

I have created an image with your script for the TL-WDR4300.

I have used the `-sysupgrade.img` to maintain my previous configuration.
After rebooting, I had the USB stick mounted and the system has been upgraded.
The problem is that `/` is not mounted to the USB stick.

Since I could not find any other possibility to contact you, I am trying this, even if this is not the proper way to ask such questions :)

**Comment by zetxx** [comment]
you can login through ssh or telnet and check on which state is stuck, please take a look here 
https://github.com/attila-lendvai/openwrt-auto-extroot#login

**Comment by attila-lendvai** [comment]
i'm not sure i understand you, but if i read you correctly, then that is not supposed to work.

openwrt doesn't promise to be binary compatible between upgrades. when you upgrade a non-extroot openwrt then it overwrites the entire flash, and if you chose to keep the config files then it will most probably not work between major openwrt releases.

or if by mean that you retained your old configuration that will also not work, because the flash my script builds has important details in the config files in it, e.g. in /etc/config/fstab, and if you retain your config, then they will not be used.

if i lived forever then ideally this should be implemented by updating the current config on demand, and then your scenario would work, but that'd be much more work to implement.

if i misunderstood you then let me know. otherwise close the ticket.
